### ISSUE TITLE
Compose with R8 enabled crashes and has coil in the stacktrace

### ISSUE THREAD

**Issue by ColtonIdle** [coil-kt/coil#1054]
I'm using `org.jetbrains.compose:compose-gradle-plugin:1.0.1-rc2` which has support for kotlin 1.6.10

It only crashes with r8 enabled.

AGP: `com.android.tools.build:gradle:7.2.0-alpha03`

```
Process: com.rollertoaster.app.free, PID: 7589
    java.lang.IllegalAccessError: Method 'void android.view.View.onAnimationEnd()' implementing interface method 'void coil.target.Target.onAnimationEnd()' is not public (declaration of 'androidx.compose.ui.platform.AndroidComposeView' appears in /data/app/~~748AKLjfkLAJjjkOO==/com.rollertoaster.app.free-lpDegrave8374JFk==/base.apk)
        at androidx.compose.ui.platform.Wrapper_androidKt.setContent(Unknown Source:0)
        at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(Unknown Source:24)
        at androidx.compose.ui.platform.AbstractComposeView.onAttachedToWindow(Unknown Source:16)
        at android.view.View.dispatchAttachedToWindow(View.java:20753)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3490)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2613)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Sorry if this is the wrong place to file. Trying to be proactive.

**Comment by colinrtwhite** [comment]
Hmm I would try downgrading to AGP `7.1.0-beta` and see if it still crashes (it uses an older R8 version). I'd also file an issue on the R8 tracker since R8 + Compose works for me locally using `7.1.0-beta`.

Also it looks like you're using the Compose desktop plugin, which Coil doesn't support: https://github.com/coil-kt/coil/issues/842

**Comment by ColtonIdle** [comment]
I've been using desktop compose plugin, but I don't build anything except an android app. I just use the desktop module to test my compose UI on local jvm instead of a real device. 😬 

I will try 7.1.0-beta. Thanks for the quick response.
