### ISSUE TITLE
Problem decoding into existing bitmap (Android 4.1)

### ISSUE THREAD

**Issue by slartus** [coil-kt/coil#1059]
**Describe the bug**
Error on load image at Android 4.1

**To Reproduce**
run android API16 (4.1)
take any path from iconUrl attribute https://raw.githubusercontent.com/slartus/4pdaClient-plus/master/forum_struct.json
and use imageView.load(path)

repo: https://github.com/slartus/CoilExperiments

**Logs/Screenshots**
W/System.err: java.lang.IllegalArgumentException: Problem decoding into existing bitmap
W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:537)
W/System.err:     at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.kt:173)
W/System.err:     at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.kt:27)
W/System.err:     at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:39)
W/System.err:     at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:438)
W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Version**
 io.coil-kt:coil:1.4.0
 compileSdk 31
 minSdk 16
 targetSdk 30

**Comment by slartus** [comment]
i must just use https://coil-kt.github.io/coil/gifs/
