### ISSUE TITLE
Video Thumbnail issue setDataSource failed: status = 0xFFFFFFEA

### ISSUE THREAD

**Issue by yehia2030** [coil-kt/coil#1139]
**Describe the bug**
when trying to load image thumbnail from online video i got this error setDataSource failed: status = 0xFFFFFFEA

**To Reproduce**

    @Composable
    fun VideoThumbnailLoader(
    modifier: Modifier = Modifier,
    videoLink: String?,
    ) {
    val context = LocalContext.current
    val imageLoader = ImageLoader.Builder(context).logger(DebugLogger()).build()
    val model =
        ImageRequest.Builder(context = context)
            .data(data = "https://mobileapidev.rundivo.com/StoryMediaFiles/70/a6c85f50-3038-4efa-a529-43e51a4d7886.mp4")
            .apply(block = {
                decoderFactory(VideoFrameDecoder.Factory())
                videoFrameMillis(2000)
                size(200)
                listener(onError = { request, result -> println(result.throwable.message + "Error") },
                    onStart = { println("started") })
            }).build()

    Image(
        modifier = modifier,
        painter = rememberAsyncImagePainter(model, imageLoader = imageLoader),
        contentDescription = stringResource(id = R.string.video_thumbnail),
        contentScale = ContentScale.Crop
    )
    LaunchedEffect(key1 = true) {
        imageLoader.execute(model)
    }
}

 
**Logs/Screenshots**
![Screenshot 2022-02-13 005420](https://user-images.githubusercontent.com/25590577/153731379-8c8d5425-490a-4d7f-92c3-6ceea49c2852.jpg)

**Version**
2.0.0-alpha08 and i run the emulator on API 30

**Comment by yehia2030** [comment]
and this is when use imageLoader.enqueu 


      E/RealImageLoader: java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
        at android.media.MediaMetadataRetriever.setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:244)
        at coil.decode.VideoFrameDecoder.setDataSource(VideoFrameDecoder.kt:175)
        at coil.decode.VideoFrameDecoder.decode(VideoFrameDecoder.kt:36)
        at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:198)
        at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:126)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
        at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:125)
        at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
        at coil.intercept.EngineInterceptor$execute$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        I/RealImageLoader: 🚨 Failed - https://mobileapidev.rundivo.com/StoryMediaFiles/70/a6c85f50-3038-4efa-                        a529-43e51a4d7886.mp4 - java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
        I/System.out: setDataSource failed: status = 0xFFFFFFEAError
        D/skia: --- Failed to create image decoder with message 'unimplemented'
    --- Failed to create image decoder with message 'unimplemented'
        D/HostConnection: HostConnection::get() New Host Connection established 0xee9a8e20, tid 5659
        D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_2 
        I/RealImageLoader: ☁️  Successful (NETWORK) - https://mobileapidev.rundivo.com/StoryMediaFiles/70/a6c85f50-3038-4efa-a529-43e51a4d7886.mp4

**Comment by colinrtwhite** [comment]
Unfortunately this is likely a device specific issue it works on my test devices in the sample app (see screenshot). [Here's another library that encountered the error with Samsung phones](https://github.com/react-native-cameraroll/react-native-cameraroll/issues/239).

<img src="https://user-images.githubusercontent.com/5580160/153772932-e68b27d5-6905-4d58-9572-bc76b040b621.png" width=50%/>

**Comment by yehia2030** [comment]
i will test it on another phone and give you the feedback thanks again

**Comment by AntonLearnsCS** [comment]
@yehia2030 hello did you ever get it to work on another device? Having this issue on Google Pixel 7 with a similar request as such:
```
  val model = ImageRequest.Builder(LocalContext.current)
                        .data(mainViewModel.pictureOfDay.observeAsState().value?.url)
                        .videoFrameMillis(3000).size(200)
                        .decoderFactory { result, options, _ ->
                            VideoFrameDecoder(
                                result.source,
                                options
                            )
                        }
                        .build()
                    val imageLoader = ImageLoader.Builder(LocalContext.current).logger(DebugLogger()).build()

                    AsyncImage(
                        model = model,
                        "Picture of the day",
                        placeholder = painterResource(R.drawable.asteroid_safe),
                        imageLoader = imageLoader,
                        modifier = Modifier.fillMaxSize(.5F).padding(5.dp),
                        contentScale = ContentScale.Crop,
                        onSuccess = {},
                        onError = {},
                        onLoading = {})
```
