### ISSUE TITLE
SVG and GIF

### ISSUE THREAD

**Issue by nacho007** [coil-kt/coil#1162]
**Describe the bug**
The SVG image is not loaded at all.

**To Reproduce**
Added :
```
    implementation("io.coil-kt:coil:1.4.0")
    implementation("io.coil-kt:coil-svg:1.4.0")
    implementation("io.coil-kt:coil-gif:1.4.0")

```

and:

```
override fun newImageLoader(): ImageLoader {
        return ImageLoader.Builder(applicationContext)
            .componentRegistry {
                add(SvgDecoder(applicationContext))
            }
            .componentRegistry {
                if (SDK_INT >= 28) {
                    add(ImageDecoderDecoder(applicationContext))
                } else {
                    add(GifDecoder())
                }
            }
            .crossfade(false)
            .logger(DebugLogger())
            .okHttpClient {
                OkHttpClient.Builder()
                    .cache(CoilUtils.createDefaultCache(applicationContext))
                    .build()
            }
            .build()
    }
```

**Logs/Screenshots**

```
E/RealImageLoader: java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.
        at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.kt:184)
        at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.kt:27)
        at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:39)
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:438)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 I/RealImageLoader: 🏗  Cancelled - https://path/img/flags/UY.svg
```

**Version**
1.4.0

**Comment by nacho007** [comment]
```
.componentRegistry {
                add(SvgDecoder(applicationContext))
                if (Build.VERSION.SDK_INT >= 28) {
                    add(ImageDecoderDecoder(applicationContext))
                } else {
                    add(GifDecoder())
                }
            }
```

This is the solution
