### ISSUE TITLE
Handle http error 429 too many requests

### ISSUE THREAD

**Issue by LunarX** [coil-kt/coil#1227]
**Describe the bug**
We're using coil version `2.0.0-rc02`. We use coil to display thumbnails in an image gallery. When we use the fast scrollbar to browse images, we sometimes receive an `http error 429` "too many requests" from our backend because we loaded too many thumbnails in a short amount of time.

**To Reproduce**
- Create an image gallery with a lot of images
- Add a scrollbar
- Browse quickly enough using the scrollbar to trigger more requests than the backend can handle (e.g. go up and down quickly using the scrollbar)
- Observe that some pictures thumbnails api call failed due to "too many requests" `http error 429`
 

**Logs/Screenshots**
```
I/RealImageLoader: 🚨 Failed - https://... - coil.network.HttpException: HTTP 429: 
2022-04-06 14:43:56.627 E/RealImageLoader: coil.network.HttpException: HTTP 429: 
        at coil.fetch.HttpUriFetcher.executeNetworkRequest(HttpUriFetcher.kt:227)
        at coil.fetch.HttpUriFetcher.access$executeNetworkRequest(HttpUriFetcher.kt:30)
        at coil.fetch.HttpUriFetcher$executeNetworkRequest$1.invokeSuspend(Unknown Source:15)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

![illustration](https://user-images.githubusercontent.com/32095402/161976191-47277cb7-e96b-4594-a1f3-03ad202823ee.png)
> The failed pictures display our "default thumbnail" 

**Version**
`2.0.0-rc02`

**Comment by colinrtwhite** [comment]
There's no clear action to take here as this is an error triggered by your backend due to launching too many image requests in a short period of time. What's the expected behaviour here?

**Comment by colinrtwhite** [comment]
@sirambd This sounds like a good candidate for a custom `Interceptor`. You can suspend, delay, or cancel calls based on custom logic.

**Comment by sirambd** [comment]
Okay I understand @colinrtwhite but I think it's a pity that coil doesn't do it automatically, as I didn't have this problem with glide.
It would be interesting to have an extension for recyclerview that limits the loading from remote when scrolling.
