### ISSUE TITLE
RealImageLoader: java.lang.NoClassDefFoundError: okio.FileSystem

### ISSUE THREAD

**Issue by coreform** [coil-kt/coil#1270]
**Describe the bug**
Trying to use coil for the first time, particularly to load svgs:

```
    implementation "io.coil-kt:coil:2.0.0"
    implementation "io.coil-kt:coil-svg:2.0.0"
```
Loading into a TextView background just to be different:
```
svgLoader = ImageLoader.Builder(context)
            .logger(DebugLogger())
            .components(fun ComponentRegistry.Builder.() {
                add(SvgDecoder.Factory())
            }).build()

```

**To Reproduce**
See above.

**Logs/Screenshots**
`RealImageLoader: java.lang.NoClassDefFoundError: okio.FileSystem
        at coil.disk.DiskCache$Builder.<init>(DiskCache.kt:119)
        at coil.util.SingletonDiskCache.get(Utils.kt:278)
        at coil.ImageLoader$Builder$build$2.invoke(ImageLoader.kt:521)
        at coil.ImageLoader$Builder$build$2.invoke(ImageLoader.kt:521)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at coil.fetch.HttpUriFetcher.readFromDiskCache(HttpUriFetcher.kt:126)
        at coil.fetch.HttpUriFetcher.fetch(HttpUriFetcher.kt:39)
        at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:165)
        at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122)
        at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.NoSuchFieldError: No field Companion of type Lokio/ByteString$Companion; in class Lokio/ByteString; or its superclasses (declaration of 'okio.ByteString' appears in /data/app/~~c4MF59LpxUEg4jwWezxJiw==/packagenamewashere-HBvFTnmvN0sL7ZgbGoXorQ==/base.apk!classes12.dex)
        at okio.internal._PathKt.<clinit>(-Path.kt:26)
        at okio.internal._PathKt.commonToPath(Unknown Source:0)
        at okio.Path$Companion.get(Path.kt:118)
        at okio.Path$Companion.get$default(Path.kt:118)
        at okio.FileSystem.<clinit>(FileSystem.kt:143)
        at coil.disk.DiskCache$Builder.<init>(DiskCache.kt:119) 
        at coil.util.SingletonDiskCache.get(Utils.kt:278) 
        at coil.ImageLoader$Builder$build$2.invoke(ImageLoader.kt:521) 
        at coil.ImageLoader$Builder$build$2.invoke(ImageLoader.kt:521) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at coil.fetch.HttpUriFetcher.readFromDiskCache(HttpUriFetcher.kt:126) 
        at coil.fetch.HttpUriFetcher.fetch(HttpUriFetcher.kt:39) 
        at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:165) 
        at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122) 
        at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41) 
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) `

**Version**
2.0.0

**Comment by colinrtwhite** [comment]
Please ask usage questions in Github Discussions.
