### ISSUE TITLE
Displaying local images (from Gallery) extremely slow

### ISSUE THREAD

**Issue by kroussevrb** [coil-kt/coil#1337]
**Describe the bug**
Implement the simplest possible grid of gallery images from the device's storage either using compose (LazyColumn with Rows or LazyVerticalGrid (but its performance is even worse) or Android Views (RecyclerView and ImageView). Use `AsyncImage` for the Compose implementation or Coil loader into ImageView, doesn't matter.

Start scrolling. Some images (absolutely regular .jpg files with regular sizes) load extremely slowly - anywhere between 0.5 seconds and 5 seconds each. No explanation. No errors in the logs.

Try every possible combination of parameters in the image request builders. Different dispatchers, thread pools with different thread sizes, thread priorities, turning on/off memory and disk cache, setting up memory cache with different options, passing lifecycles, turning hardware on/off, bitmap rendering options changes.. literally everything that the builder provides. No success. Try with a release build (for Compose) - same result.

Additionally, sometimes there is a single image that throws an error while being decoded. The error is caught internally and displayed in LogCat. For some reason all image loading stops.

**To Reproduce**
As described above a vanilla implementation using compose or android view will do, and use a real device with real photos made with camera and/or downloaded from the internet.

**Logs/Screenshots**
When profiling this, it becomes apparent how all the fetcher/interceptor/decoder threads start sleeping while there are no other threads in the app working - this causes the delay in image loading. There is no obvious explanation of why that happens.

**Version**
Latest at time of writing

Here is the code

```
  implementation("io.coil-kt:coil-compose:2.1.0") {
    exclude(group = "com.squareup.okhttp3")
  }
```

In the `Application` class

```
    class NamingThreadFactory(private val prefix: String) : ThreadFactory {
      private val threadNumber: AtomicInteger = AtomicInteger(0)
      override fun newThread(r: Runnable): Thread {
        val t = Executors.defaultThreadFactory().newThread(r)
        t.name = prefix + threadNumber.addAndGet(1)
        // t.priority = 9/10 // Out of desperation you can try playing with the priorities 
        return t
      }
    }
    val asd = Executors.newFixedThreadPool(5, NamingThreadFactory(prefix = "Coil-")).asCoroutineDispatcher() // You can try passing different executors with different prefixes (i.e. "Decoder-", "Fetcher-" etc to see which ones stall)


    Coil.setImageLoader(
      ImageLoader.Builder(this)
        .logger(DebugLogger()) // Logs NO errors
        .memoryCache {
          MemoryCache.Builder(this)
            .maxSizePercent(0.9) // Tried with 0.25 too
            .build()
        }
//        .diskCache {
//          DiskCache.Builder()
//            .directory(this.cacheDir.resolve("image_cache"))
//            .maxSizePercent(0.2)
//            .build()
//        }
        .precision(Precision.INEXACT)
        .error(R.drawable.ic_error)
        .allowHardware(false) // Tried with `on` too
        //pass whole view as lifecycle to stop cancellations? // Tried that, it had no effect
        .okHttpClient {
          OkHttpClient() // It is actually not needed here, because we make no network requests in this example
        }
        .networkCachePolicy(CachePolicy.DISABLED)// Try with ENABLED too
        .networkObserverEnabled(false)
        .memoryCachePolicy(CachePolicy.DISABLED) // Try with ENABLED too
        .diskCachePolicy(CachePolicy.DISABLED)
        .fetcherDispatcher(asd) // You can try with this or any other dispatcher (Dispatchers.Default/Main/IO), it only makes difference for the worse depending on what you pass
        .decoderDispatcher(asd) // You can try passing the same dispatcher constructed above or different ones, it can only get worse to a different degree
        .interceptorDispatcher(asd)
        .transformationDispatcher(asd)
        .build()
    )
```

In your compose `LazyColumn` with image grid with 3 columns:

```
                val density = LocalDensity.current
                val boxSize = remember {
                  with(density) { (this@BoxWithConstraints.maxWidth / 3).toPx() }.toInt()
                }
                val painter = rememberAsyncImagePainter(
                  model = ImageRequest.Builder(context).data(image).size(boxSize).build(),
                  imageLoader = context.imageLoader
                )
                AsyncImage(
                  model = painter.request,
                  contentDescription = "",
                  contentScale = ContentScale.Crop,
                  modifier = Modifier
                    .size(this@BoxWithConstraints.maxWidth / 3)
                    .padding(4.dp)
                    .size(120.dp)
```

How to get the list of local images:

```
context.contentResolver.query(
          MediaStore.Images.Media.EXTERNAL_CONTENT_URI,
          arrayOf(MediaStore.Images.Media._ID),
          null,
          null,
          MediaStore.Images.Media.DATE_ADDED + " DESC"
        )?.use { cursor ->
          val columnIndex = cursor.getColumnIndex(MediaStore.Images.Media._ID)
          if (columnIndex >= 0) {
            (0 until cursor.count).map {
              cursor.moveToNext()
              Uri.withAppendedPath(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, cursor.getInt(columnIndex).toString())
            }
          } else {
            emptyList()
          }

        } ?: emptyList()
```

<img width="970" alt="Screen Shot 2022-06-24 at 10 27 12" src="https://user-images.githubusercontent.com/17250295/175485479-e29ffe2a-6f0a-402d-9fea-ca2cad092126.png">

Reproduced on Huawei P20 Pro with Android 10 and on a coworker's device (don't know what it was)

----
AndroidView implementation with `RecyclerView`

```
    override fun onBindViewHolder(holder: ViewHolder, position: Int) {
        val itemViewModel:ItemViewModel = imageList[position]
        runCatching {
            holder.imageView.load(
                itemViewModel.image,
                builder = {
                    this.size(360)
                        .placeholder(R.drawable.ic_launcher_background)
                        .error(R.drawable.ic_launcher_foreground)
                        .allowHardware(true)
                        //.fetcherDispatcher(Executors.newFixedThreadPool(5).asCoroutineDispatcher())
                        //.decoderDispatcher(Executors.newFixedThreadPool(5).asCoroutineDispatcher())
                        .interceptorDispatcher(Dispatchers.IO)
                        .fetcherDispatcher(Dispatchers.IO)
                        .decoderDispatcher(Dispatchers.IO)
                        .memoryCachePolicy(CachePolicy.DISABLED)
                        .diskCachePolicy(CachePolicy.DISABLED)
                        .precision(Precision.INEXACT)
                        .networkCachePolicy(CachePolicy.DISABLED)
                }
            )
        }
    }
```

-------

In both Compose and AndroidView implementations, I swapped Coil for Glide and it worked extremely well. However Glide has its own problems (doesn't support KSP among other things).

**Comment by colinrtwhite** [comment]
I wouldn’t use `rememberAsyncImagePainter` in combination with `AsyncImage`. You should use one or the other. I suspect that’s your issue.

**Comment by kroussevrb** [comment]
@colinrtwhite

That looks as if it could be a great improvement (it will be better if you change the API to make this impossible to get wrong (https://blog.danlew.net/2022/06/22/maintaining-software-correctness/))
However, for some reason the library stops loading ANY images in the grid in the moment ONE of them throws an exception:

```
java.io.IOException: read failed: ENOTCONN (Transport endpoint is not connected)
2022-06-29 13:10:54.650 18314-18539/com.asd.myapplication W/System.err:     at libcore.io.IoBridge.read(IoBridge.java:523)
2022-06-29 13:10:54.650 18314-18539/com.asd.myapplication W/System.err:     at java.io.FileInputStream.read(FileInputStream.java:313)
2022-06-29 13:10:54.650 18314-18539/com.asd.myapplication W/System.err:     at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:975)
2022-06-29 13:10:54.650 18314-18539/com.asd.myapplication W/System.err:     at okio.InputStreamSource.read(JvmOkio.kt:94)
2022-06-29 13:10:54.650 18314-18539/com.asd.myapplication W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at okio.ForwardingSource.read(ForwardingSource.kt:29)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.kt:193)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at okio.RealBufferedSource.request(RealBufferedSource.kt:206)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at okio.PeekSource.read(PeekSource.kt:50)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
2022-06-29 13:10:54.651 18314-18539/com.asd.myapplication W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
```

So I cannot verify that this fixes the problem as when I get to the patch of photos that is hard for Coil to display, this happens and it stops there.

If it helps, this is also printed in the logs

```
W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:44.465027, limit is:60The moving distance of Y is:71.83533, limit is:60
2022-06-29 13:10:34.144 18314-18314/com.asd.myapplication W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:47.36902, limit is:60The moving distance of Y is:73.55359, limit is:60
2022-06-29 13:10:34.945 18314-18314/com.asd.myapplication W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:29.301208, limit is:60The moving distance of Y is:69.30286, limit is:60
2022-06-29 13:10:35.664 18314-18314/com.asd.myapplication W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:45.32721, limit is:60The moving distance of Y is:109.28345, limit is:60
2022-06-29 13:10:36.482 18314-18314/com.asd.myapplication W/HiTouch_PressGestureDetector: Touch pointer move a lot. The moving distance of X is:47.15143, limit is:60The moving distance of Y is:87.027954, limit is:60
```

**Comment by colinrtwhite** [comment]
The first exception looks the InputStream is being closed prematurely. This may be a local issue with your data source.

Sorry, but I’m unable to debug further without a sample that reproduces the issue.

**Comment by kroussevrb** [comment]
@colinrtwhite
