### ISSUE TITLE
Loading an SVG with `ex` dimensions seem to decode at VERY large incorrect size

### ISSUE THREAD

**Issue by spacecowboy** [coil-kt/coil#1428]
Coil 2.2.0 when trying to load this image (on an Android Emulator):

http://www.corsix.org/images/495f98eb0abe80037a8bfb0b3dfb943df9e04495.svg

Note that the image is only 14kb but coil is attempting to decode a 142mb file?

As said by @colinrtwhite : 

> Your SVG has the intrinsic dimensions width="101.484ex" height="2.843ex", which uses the ex unit (an [uncommon type](https://oreillymedia.github.io/Using_SVG/guide/units.html)) so it's possible they're being interpreted incorrectly by the SVG rendering library.

```
2022-08-31 00:39:32.474 6398-6398/com.nononsenseapps.feeder.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nononsenseapps.feeder.debug, PID: 6398
    java.lang.RuntimeException: Canvas: trying to draw too large(142657200bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
        at androidx.compose.ui.graphics.AndroidCanvas.drawImageRect-HPBpro0(AndroidCanvas.android.kt:271)
        at androidx.compose.ui.graphics.drawscope.CanvasDrawScope.drawImage-AZ2fEMs(CanvasDrawScope.kt:263)
        at androidx.compose.ui.node.LayoutNodeDrawScope.drawImage-AZ2fEMs(Unknown Source:40)
        at androidx.compose.ui.graphics.drawscope.DrawScope.drawImage-AZ2fEMs$default(DrawScope.kt:510)
        at androidx.compose.ui.graphics.painter.BitmapPainter.onDraw(BitmapPainter.kt:93)
        at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
        at coil.compose.AsyncImagePainter.onDraw(AsyncImagePainter.kt:210)
        at androidx.compose.ui.graphics.painter.Painter.draw-x_KDEd0(Painter.kt:212)
        at androidx.compose.ui.draw.PainterModifier.draw(PainterModifier.kt:281)
        at androidx.compose.ui.node.DrawEntity.draw(DrawEntity.kt:98)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:336)
        at androidx.compose.ui.node.LayoutNodeWrapper.draw(LayoutNodeWrapper.kt:326)
        at androidx.compose.ui.node.ModifiedLayoutNode.performDraw(ModifiedLayoutNode.kt:242)
        at androidx.compose.ui.node.LayoutNodeWrapper.drawContainedDrawModifiers(LayoutNodeWrapper.kt:334)
        at androidx.compose.ui.node.LayoutNodeWrapper.access$drawContainedDrawModifiers(LayoutNodeWrapper.kt:64)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:358)
        at androidx.compose.ui.node.LayoutNodeWrapper$invoke$1.invoke(LayoutNodeWrapper.kt:357)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2118)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:129)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver$observeReads$1$1.invoke(SnapshotStateObserver.kt:125)
        at androidx.compose.runtime.SnapshotStateKt__DerivedStateKt.observeDerivedStateRecalculations(DerivedState.kt:336)
        at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(Unknown Source:1)
        at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:125)
        at androidx.compose.ui.node.OwnerSnapshotObserver.observeReads$ui_release(OwnerSnapshotObserver.kt:120)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:357)
        at androidx.compose.ui.node.LayoutNodeWrapper.invoke(LayoutNodeWrapper.kt:64)
        at androidx.compose.ui.platform.RenderNodeApi29.record(RenderNodeApi29.android.kt:180)
        at androidx.compose.ui.platform.RenderNodeLayer.updateDisplayList(RenderNodeLayer.android.kt:298)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchDraw(AndroidComposeView.android.kt:1005)
        at android.view.View.draw(View.java:23198)
        at android.view.View.updateDisplayListIfDirty(View.java:22062)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
        at android.view.View.updateDisplayListIfDirty(View.java:22018)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
2022-08-31 00:39:32.474 6398-6398/com.nononsenseapps.feeder.debug E/AndroidRuntime:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:832)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Using the following code:

```
Image(
                                    painter = rememberAsyncImagePainter(
                                        model = ImageRequest.Builder(LocalContext.current)
                                            .data(imageUrl)
                                            .scale(Scale.FILL)
                                            .placeholder(placeHolder)
                                            .error(placeHolder)
                                            .precision(Precision.INEXACT)
                                            .size(1000)
                                            .build(),
                                        contentScale = ContentScale.Crop,
                                    ),
                                    contentScale = ContentScale.Crop,
                                    contentDescription = null,
                                    modifier = modifier
                                        .fillMaxWidth()
                                        .aspectRatio(16.0f / 9.0f)
                                )
```

**Comment by colinrtwhite** [comment]
@spacecowboy Thanks for filing an issue, though this appears to be working correctly. To explain:

- You've set the `size` to 1000x1000 and the content scale to `Crop`, which means the image will fill the 1000x1000 space.
- Your SVG has a roughly 726:16 aspect ratio meaning for the smaller dimension to be 1000, the other has to be 45375 pixels. This means the output image will be 45375 by 1000, which is too large for Android to draw.

To resolve this I'd recommend setting the scale to `Scale.FIT` so it fits to the minimal dimension instead of the maximum. Also I'd recommend using `AsyncImage` and not setting a `size` value so Coil can automatically load it at the smallest necessary size.

**Comment by spacecowboy** [comment]
Thanks for your help @colinrtwhite . I was seriously confused about what `Scale` was doing vs `ContentScale`.

I am now using `Scale.FIT` everywhere (because this is what I actually wanted), while using `ContentScale.Crop` to fill the image bounds.

And the following interceptor catches the rare image which comes way too large

```
/**
 * Ensures an error is returned instead of rendering images that are likely to trigger memory errors
 * onDraw - but are not SO large as too cause a OOM exception during decode.
 */
class TooLargeImageInterceptor : Interceptor {
    override suspend fun intercept(chain: Interceptor.Chain): ImageResult {

        return when (val result = chain.proceed(chain.request)) {
            is ErrorResult -> result
            is SuccessResult -> {
                val sumPixels = result.drawable.intrinsicWidth * result.drawable.intrinsicHeight

                if (sumPixels > MAX_PIXELS) {
                    return ErrorResult(
                        chain.request.error,
                        chain.request,
                        RuntimeException("Image was (probably) too large to render within memory constraints: ${result.drawable.intrinsicWidth} x ${result.drawable.intrinsicHeight} > 2500 x 2500")
                    )
                } else
                    result
            }
        }
    }

    companion object {
        const val MAX_PIXELS = 2500 * 2500
    }
}
```

:beers:
