### ISSUE TITLE
The image filename has chinese, load failed.

### ISSUE THREAD

**Issue by xilost** [coil-kt/coil#1467]
**Describe the bug**
The image filename has chinese, load failed.

**To Reproduce**
this image url  https://file.hd.weibo.com/isale/content/16633155108051079889028/微信图片_20220211104359.jpg

**Logs/Screenshots**
java.lang.IllegalArgumentException: Unexpected char 0x87ba at 23 in content-disposition value:  attachment; filename="螺狮粉.png"
        at okhttp3.Headers$Companion.checkValue(Headers.kt:450)
        at okhttp3.Headers$Companion.access$checkValue(Headers.kt:362)
        at okhttp3.Headers$Builder.add(Headers.kt:261)
        at okhttp3.Headers$Builder.add(Headers.kt:253)
        at coil.network.CacheResponse.<init>(CacheResponse.kt:28)
        at coil.fetch.HttpUriFetcher.toCacheResponse(HttpUriFetcher.kt:255)
        at coil.fetch.HttpUriFetcher.fetch(HttpUriFetcher.kt:55)
        at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:165)
        at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122)
        at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Version**
2.2.0

addUnsafeNonAscii replace add.

**Comment by colinrtwhite** [comment]
Hmm the fact that the replacement method has `unsafe` in the name makes me think we shouldn't migrate to it as the default for `ImageRequest.addHeader` (cc @yschimke). If you need this behaviour I'd recommend setting the headers manually:

```kotlin
val headers = Headers.Builder()
    .addUnsafeNonAscii("name", "value")
    .build()
imageLoader.enqueue(imageRequest.headers(headers).build())
```
