### ISSUE TITLE
ContentUriFetcher.kt line 45

### ISSUE THREAD

**Issue by shlauzer** [coil-kt/coil#1605]
**Describe the bug**
7 non-fatal events in Firebase Crashlytics: _**Non-fatal Exception: java.io.FileNotFoundException open failed: ENOENT (No such file or directory)**_

**To Reproduce**
Unknown

**Logs/Screenshots**
# Crashlytics - Stack trace
# Application: io.breezeventures.mb
# Platform: android
# Version: 1.5.0-GMS (1084)
# Issue: 8eed04915b7fe199b255eddd34f61504
# Session: 63D7BFF3026300014728A2A7049438B8_DNE_0_v2
# Date: Mon Jan 30 2023 20:04:09 GMT+0700 (Новосибирск, стандартное время)

Non-fatal Exception: java.io.FileNotFoundException: open failed: ENOENT (No such file or directory)
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderProxy.java:705)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1702)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1518)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:1202)
       at coil.fetch.ContentUriFetcher.fetch(ContentUriFetcher.kt:45)
       at coil.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:165)
       at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:122)
       at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
       at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Version**
2.2.2

**Comment by colinrtwhite** [comment]
It looks like you're attempting to open an asset file that doesn't exist. This doesn't seem like a bug internal to Coil.

**Comment by shlauzer** [comment]
> It looks like you're attempting to open an asset file that doesn't exist. This doesn't seem like a bug internal to Coil.
As I can see, `coil.fetch.ContentUriFetcher` tries to open an asset.
