### ISSUE TITLE
Coil tries to use Context#cacheDir even when a custom disk cache directory is set

### ISSUE THREAD

**Issue by saket** [coil-kt/coil#1754]
**Describe the bug**
When Coil is used to load an image with disk caching disabled, it tries to access `Context#cacheDir` even when a custom cache directory is set. I'm using Coil's read image loader in a paparazzi test where `cacheDir` returns null, causing an NPE.

**To Reproduce**
```kotlin
val fakeCacheSystem = FakeFileSystem()
val loader = ImageLoader.Builder(context)
  .diskCache(
    DiskCache.Builder()
      .fileSystem(fakeCacheSystem)
      .directory(fakeCacheSystem.workingDirectory)
      .build()
  )
  .build()

loader.execute(
  ImageRequest.Builder(context)
    .data("foo")
    .memoryCachePolicy(CachePolicy.ENABLED)
    .diskCachePolicy(CachePolicy.DISABLED)
    .build()
)
```

Setting `diskCachePolicy` to `CachePolicy.ENABLED` fixes this problem.

**Stacktrace**
```kotlin
java.lang.NullPointerException
	at coil.util.-Utils.getSafeCacheDir(Utils.kt:174)
	at coil.decode.ImageSources.create(ImageSource.kt:68)
	at coil.fetch.HttpUriFetcher.toImageSource(HttpUriFetcher.kt:268)
	at coil.fetch.HttpUriFetcher.fetch(HttpUriFetcher.kt:97)
	at coil.fetch.HttpUriFetcher$fetch$1.invokeSuspend(HttpUriFetcher.kt)
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46)
	at coil.intercept.EngineInterceptor.intercept(EngineInterceptor.kt:73)
	at coil.intercept.RealInterceptorChain.proceed(RealInterceptorChain.kt:25)
	at coil.RealImageLoader$executeMain$result$1.invokeSuspend(RealImageLoader.kt:191)
	at coil.RealImageLoader.executeMain(RealImageLoader.kt:182)
	at coil.RealImageLoader$execute$2$job$1.invokeSuspend(RealImageLoader.kt:133)
```

**Version**
2.3.0

**Comment by colinrtwhite** [comment]
Good catch, thanks!

**Comment by colinrtwhite** [comment]
This is a bit tricky unfortunately. Coil needs to create a temporary file if the `Fetcher` returns a `BufferedSource`, but the `Decoder` requires an on-disk file. Additionally, it has to be able to do that outside of the `DiskCache` directory and even if `DiskCache` is null.

To solve this completely I think we'll have to add something like `ImageLoader.Builder.temporaryFileFactory`, though I'm not sure that's the best design. I think it's best to punt this until 3.0 as we'll have to refactor out all `Context` references.

For the moment I've changed `context.cacheDir` to be called lazily which should work in most cases. Only a few decoders like `VideoFrameDecoder` need a file due to Android's API limitations.

**Comment by saket** [comment]
sounds good, thank you!
