### ISSUE TITLE
GifDecoder making recyclerview scroll to the top when scrolling

### ISSUE THREAD

**Issue by NobilityDeviant** [coil-kt/coil#1792]
**Describe the bug**

Whenever I am scrolling inside of a recyclerview with the GifDecoder being used on certain images, it throws an error:

`java.io.InterruptedIOException: interrupted
System.err              	at okio.Timeout.throwIfReached(Timeout.kt:99)
System.err              	at okio.InputStreamSource.read(JvmOkio.kt:91)
System.err              	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
System.err              	at okio.ForwardingSource.read(ForwardingSource.kt:27)
System.err              	at coil.decode.FrameDelayRewritingSource.request(FrameDelayRewritingSource.kt:77)
System.err              	at coil.decode.FrameDelayRewritingSource.read(FrameDelayRewritingSource.kt:22)
System.err              	at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
System.err              	at android.graphics.Movie.nativeDecodeStream(Native Method)
System.err              	at android.graphics.Movie.decodeStream(Movie.java:60)
System.err              	at coil.decode.GifDecoder$decode$2.invoke(GifDecoder.kt:40)
System.err              	at coil.decode.GifDecoder$decode$2.invoke(GifDecoder.kt:34)
System.err              	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
System.err              	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
System.err              	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
System.err              	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
System.err              	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Interruptible.kt)
System.err              	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
System.err              	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:159)
System.err              	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
System.err              	at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
System.err              	at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:40)
System.err              	at coil.decode.GifDecoder.decode(GifDecoder.kt:34)
System.err              	at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:199)
System.err              	at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
System.err              	at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:127)
System.err              	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
System.err              	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(EngineInterceptor.kt)
System.err              	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
System.err              	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
System.err              	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
System.err              	at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:126)
System.err              	at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
System.err              	at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
System.err              	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)`

And then it scrolls to the top.
Weird enough is that the images do seem to be loaded properly in the top row.
When enabling logging it keeps showing that when loading the gifs, it gets cancelled.

To be more specific, this is a recyclerview with viewholders looking like so:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="2dp"
    android:orientation="vertical">

    <LinearLayout
        android:id="@+id/header"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

        <TextView
            android:id="@+id/headerText"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="3dp"
            android:textColor="?colorOnPrimary"
            android:textSize="14sp" />

    </LinearLayout>

    <GridLayout
        android:id="@+id/emojiGrid"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:rowOrderPreserved="true"
        android:columnOrderPreserved="true"
        android:alignmentMode="alignMargins"
        />

</LinearLayout>`

This is just a grid that i programmatically fill like so:

`binding.emojiGrid.removeAllViews()
        binding.root.post {
            val emojis = set.getEmojis()
            if (emojis != null) {
                val emojisPerRow = binding.root.width / (set.params.width
                        + set.params.leftMargin
                        + set.params.rightMargin)
                binding.emojiGrid.columnCount = emojisPerRow
                binding.emojiGrid.rowCount = (emojis.size / emojisPerRow) + 1
                for (emoji in emojis) {
                    try {
                        var nameCheck = ""
                        var imagePath: Any? = null
                        if (emoji.emojiType == EmojiHolderType.ASSET) {
                            nameCheck = emoji.namePlusExtension
                            imagePath = emoji.assetPath
                        } else if (emoji.emojiType == EmojiHolderType.FILE) {
                            nameCheck = emoji.path
                            imagePath = emoji.file
                        }
                        if (nameCheck.isEmpty() || imagePath == null) {
                            Timber.i("Emoji data is null. NameCheck: $nameCheck ImagePath: $imagePath")
                            continue
                        }
                        var imageView: ImageView
                        if (nameCheck.endsWith(".gif")
                            && !CoreSDK.currentUser().getDisableEmojiGIf()) {
                            imageView = GifImageView(context)
                            ImageBuilder.Builder(context, imageView, imagePath)
                                .gifMode(true)
                                .buildAndShow()
                        } else {
                            imageView = ImageView(context)
                            ImageBuilder.Builder(context, imageView, imagePath)
                                .buildAndShow()
                        }
                        val params = set.params
                        val emojiParams = LinearLayout.LayoutParams(params.width, params.height)
                        emojiParams.setMargins(
                            params.leftMargin,
                            params.topMargin,
                            params.rightMargin,
                            params.bottomMargin
                        )
                        emojiParams.gravity = Gravity.CENTER_HORIZONTAL
                        val fileName = emoji.name
                        imageView.setOnClickListener {
                            setEmojiToChat(":$fileName:", editText)
                            if (set.saveToHistory) {
                                synchronized(this) {
                                    CoreSDK.prefManager().addHistoryEmoji(fileName)
                                }
                            }
                        }
                        imageView.setOnLongClickListener {
                            show(context, ":$fileName:", false)
                            true
                        }
                        val gridParams = GridLayout.LayoutParams()
                        gridParams.width = params.width
                        gridParams.height = params.height
                        gridParams.setMargins(
                            params.leftMargin,
                            params.topMargin,
                            params.rightMargin,
                            params.bottomMargin
                        )
                        gridParams.setGravity(Gravity.START)
                        gridParams.columnSpec = GridLayout.spec(
                            GridLayout.UNDEFINED,
                            0f
                        )
                        gridParams.rowSpec = GridLayout.spec(
                            GridLayout.UNDEFINED,
                            0f
                        )
                        binding.emojiGrid.addView(
                            imageView,
                            gridParams
                        )
                    } catch (e: Exception) {
                        CoreSDK.logError(e)
                    }
                }
            }
        }`

These reyclerviews are inside of a ViewPager2 if that helps.
This all used to work while using Glide.

The code:

`ImageBuilder.Builder(context, imageView, imagePath)
                                .gifMode(true)
                                .buildAndShow()`

Is just my own builder that uses coil at it's core.
with this option enabled:

`if (isGif) {
            imageLoader.apply {
                components {
                    if (SDK_INT >= 28) {
                        add(ImageDecoderDecoder.Factory())
                    } else {
                        add(GifDecoder.Factory())
                    }
                }
            }
        }`

Is when the issue happens. If it's off it works fine.

I have tried changing the timeouts and tweaking certain options with no success.

**Version**
What library version are you using? Does this occur on a specific API level or Android device?

I am using the latest versions:

implementation("io.coil-kt:coil:2.4.0")
implementation("io.coil-kt:coil-gif:2.4.0")

and since this is happening with the GifDecoder it is on Android 7.0

**Comment by NobilityDeviant** [comment]
I am sorry for the horrible formatting. let me use a bin service

**Comment by NobilityDeviant** [comment]
also it is not a binding issue.
i am not re-adding the recyclerview adapter.
it does not rebind any of the rows
everything is already 100% loaded except the images
maybe preloading them if possible might work? let me try

**Comment by colinrtwhite** [comment]
Sorry, but there isn't enough here to reproduce the issue. Do you have a sample project that reproduces the issue? The `coil-sample-view` app in this repo loads GIFs in a RecyclerView and doesn't experience this issue.

This sounds potentially related to the fact that GIF images not saved to the memory cache. It's currently expected behaviour that they will be reloaded asynchronously each time you start a new `ImageRequest`.

**Comment by colinrtwhite** [comment]
Please file a new issue with a repro project if this is still failing.
