### ISSUE TITLE
coil.decode.ImageDecoderDecoder -> Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by vitorpamplona** [coil-kt/coil#1869]
**Describe the bug**
ImageDecoder still sometimes doesn't close a fileInputStream's close method.  

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
  at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1986)
  at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
  at java.io.FileInputStream.finalize(FileInputStream.java:503)
  at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
  at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
  at java.lang.Daemons$Daemon.run(Daemons.java:140)
  at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.Throwable: Explicit termination method 'close' not called
  at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
  at dalvik.system.CloseGuard.open(CloseGuard.java:257)
  at java.io.FileInputStream.<init>(FileInputStream.java:176)
  at android.graphics.ImageDecoder.createFromFile(ImageDecoder.java:317)
  at android.graphics.ImageDecoder.-$$Nest$smcreateFromFile(Unknown Source:0)
  at android.graphics.ImageDecoder$FileSource.createImageDecoder(ImageDecoder.java:585)
  at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1827)
  at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1819)
  at coil.decode.ImageDecoderDecoder$decode$drawable$1.invoke(ImageDecoderDecoder.kt:188)
  at coil.decode.ImageDecoderDecoder$decode$drawable$1.invoke(ImageDecoderDecoder.kt:50)
  at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
  at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:8)
  at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:4)
  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:159)
  at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
  at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
  at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:40)
  at coil.decode.ImageDecoderDecoder.decode(ImageDecoderDecoder.kt:50)
  at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:199)
  at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
  at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:127)
  at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
  at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
  at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
  at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
  at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
  at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:126)
  at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
  at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**To Reproduce**
I am wondering if this is a co-routine being canceled at the right time to create the bug. Because I cannot reproduce this reliably. But it happens enough times that it becomes an issue. 

**Logs/Screenshots**
If applicable, [add logs](https://coil-kt.github.io/coil/faq/#how-do-i-enable-logging) or screenshots to help explain your problem.

**Version**
```gradle
implementation "io.coil-kt:coil-compose:2.4.0"
implementation "io.coil-kt:coil-gif:2.4.0"
implementation "io.coil-kt:coil-svg:2.4.0"
```

with 

```kotlin
Coil.setImageLoader {
    ImageLoader.Builder(context).components {
        if (Build.VERSION.SDK_INT >= 28) {
            add(ImageDecoderDecoder.Factory())
        } else {
            add(GifDecoder.Factory())
        }
        add(SvgDecoder.Factory())
    }.logger(DebugLogger())
        .diskCache { SingletonDiskCache.get(context.applicationContext) }
        .okHttpClient { HttpClient.getHttpClient() }
        .respectCacheHeaders(false)
        .build()
}
```

**Comment by colinrtwhite** [comment]
Which API level did you trigger this on? IIRC this was a bug in `ImageDecoder` that is fixed in API 34 (potentially earlier).

**Comment by vitorpamplona** [comment]
Compiled on 34, target SDK 34. Running on a Pixel 7 on 33, latest update.

**Comment by colinrtwhite** [comment]
Hmm I think this is likely an AOSP bug. From the stack trace we can see the `FileInputStream` is allocated by `ImageDecoder` (Coil doesn't get a reference). Coil must always close the `ImageDecoder` and the underlying file that the `ImageDecoder` is reading [here](https://github.com/coil-kt/coil/blob/main/coil-gif/src/main/java/coil/decode/ImageDecoderDecoder.kt#L86) given it's in a finally block.

Interestingly, the `ImageDecoder.close` doc says to not call that method manually, but how else will the underlying stream be closed if it isn't called?

**Comment by colinrtwhite** [comment]
Chatted with folks on the Google team and they're not sure how this could happen as `ImageDecoder` should always free the internal file instance. Have you found a way to reproduce this?

**Comment by colinrtwhite** [comment]
Going to close this out as I haven't been able to reproduce locally and Coil doesn't have access to the underlying input stream mentioned in the `LeakedClosableViolation`. This seems like it could be an AOSP issue.

**Comment by vitorpamplona** [comment]
I just saw it happening again with coil 3. Now it is clear that it is something with the Gif decoder. 

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. (Ask Gemini)
    at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:2007)
    at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
    at java.io.FileInputStream.finalize(FileInputStream.java:662)
    at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
    at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
    at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
    at java.lang.Daemons$Daemon.run(Daemons.java:131)
    at java.lang.Thread.run(Thread.java:1012)
   Caused by: java.lang.Throwable: Explicit termination method 'close' not called
    at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
    at dalvik.system.CloseGuard.open(CloseGuard.java:257)
    at java.io.FileInputStream.<init>(FileInputStream.java:195)
    at android.graphics.ImageDecoder.createFromFile(ImageDecoder.java:320)
    at android.graphics.ImageDecoder.-$$Nest$smcreateFromFile(Unknown Source:0)
    at android.graphics.ImageDecoder$FileSource.createImageDecoder(ImageDecoder.java:588)
    at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1748)
    at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1740)
    at coil3.gif.AnimatedImageDecoder.decode$lambda$3(AnimatedImageDecoder.kt:164)
    at coil3.gif.AnimatedImageDecoder.$r8$lambda$LcWMVgsmqUcWBiDUbfkdZfJzy5g(Unknown Source:0)
    at coil3.gif.AnimatedImageDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
    at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:48)
    at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
    at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:40)
    at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:8)
    at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
    at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:39)
    at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:36)
    at coil3.gif.AnimatedImageDecoder.decode(AnimatedImageDecoder.kt:57)
    at coil3.intercept.EngineInterceptor.decode(EngineInterceptor.kt:189)
    at coil3.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:31)
    at coil3.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:119)
    at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
    at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
    at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
    at coil3.intercept.EngineInterceptor.execute(EngineInterceptor.kt:118)
    at coil3.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:31)
    at coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:65)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
16:07:54.014 StrictMode               D  	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

**Comment by initialjie** [comment]
> I just saw it happening again with coil 3. Now it is clear that it is something with the Gif decoder.
> 
> ```
> StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks. (Ask Gemini)
>     at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:2007)
>     at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
>     at java.io.FileInputStream.finalize(FileInputStream.java:662)
>     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:370)
>     at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:350)
>     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:322)
>     at java.lang.Daemons$Daemon.run(Daemons.java:131)
>     at java.lang.Thread.run(Thread.java:1012)
>    Caused by: java.lang.Throwable: Explicit termination method 'close' not called
>     at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
>     at dalvik.system.CloseGuard.open(CloseGuard.java:257)
>     at java.io.FileInputStream.<init>(FileInputStream.java:195)
>     at android.graphics.ImageDecoder.createFromFile(ImageDecoder.java:320)
>     at android.graphics.ImageDecoder.-$$Nest$smcreateFromFile(Unknown Source:0)
>     at android.graphics.ImageDecoder$FileSource.createImageDecoder(ImageDecoder.java:588)
>     at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1748)
>     at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1740)
>     at coil3.gif.AnimatedImageDecoder.decode$lambda$3(AnimatedImageDecoder.kt:164)
>     at coil3.gif.AnimatedImageDecoder.$r8$lambda$LcWMVgsmqUcWBiDUbfkdZfJzy5g(Unknown Source:0)
>     at coil3.gif.AnimatedImageDecoder$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
>     at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:48)
>     at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
>     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:40)
>     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:8)
>     at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:4)
>     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
>     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:156)
>     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
>     at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:39)
>     at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:36)
>     at coil3.gif.AnimatedImageDecoder.decode(AnimatedImageDecoder.kt:57)
>     at coil3.intercept.EngineInterceptor.decode(EngineInterceptor.kt:189)
>     at coil3.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:31)
>     at coil3.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:119)
>     at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
>     at coil3.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
>     at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
>     at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
>     at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
>     at coil3.intercept.EngineInterceptor.execute(EngineInterceptor.kt:118)
>     at coil3.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:31)
>     at coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:65)
>     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
>     at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
>     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
>     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
>     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
> ```
> 
> This was on the default Pixel 9 pro emulator from Android Studio's Ladybug | 2024.2.1 Patch 2, running on MacOS Sequoia 15.1.1.

v3.1.0 issue still exist

**Comment by colinrtwhite** [comment]
This is an AOSP issue with Android's `ImageDecoder` class and will need to be reported on the Google issue tracker with a way to reproduce the issue. Coil doesn't have access to the underlying `FileInputStream` opened by `ImageDecoder` and can't work around the issue.

**Comment by brinsche** [comment]
I filed a new issue with a reproducer here: https://issuetracker.google.com/issues/464515857
