### ISSUE TITLE
Coil is Not working with compose web (Js)

### ISSUE THREAD

**Issue by sunildhiman90** [coil-kt/coil#2042]
**Describe the bug**
Hi team i tried to integrate the coil compose 3.0.0-alpha02 in multiplatform project, Its working fine for android, ios and desktop targets, But not for web, For web im getting this error:

`e: java.lang.IllegalStateException: Symbol for androidx.compose.foundation/Indication.rememberUpdatedInstance$composable|-5308894476871022020[0] is unbound
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.getOwner(IrPublicSymbolBase.kt:63)
	at org.jetbrains.kotlin.ir.util.IrFakeOverrideUtilsKt.collectAndFilterRealOverrides$excludeRepeated(IrFakeOverrideUtils.kt:76)
	at org.jetbrains.kotlin.ir.util.IrFakeOverrideUtilsKt.collectAndFilterRealOverrides(IrFakeOverrideUtils.kt:83)
	at org.jetbrains.kotlin.ir.util.IrFakeOverrideUtilsKt.collectRealOverrides(IrFakeOverrideUtils.kt:42)
	at org.jetbrains.kotlin.ir.util.IrFakeOverrideUtilsKt.collectRealOverrides$default(IrFakeOverrideUtils.kt:33)
	at org.jetbrains.kotlin.backend.common.linkage.partial.ImplementAsErrorThrowingStubs.isAmbiguous(IrUnimplementedOverridesStrategy.kt:62)
	at org.jetbrains.kotlin.backend.common.linkage.partial.ImplementAsErrorThrowingStubs.postProcessGeneratedFakeOverride(IrUnimplementedOverridesStrategy.kt:33)
	at org.jetbrains.kotlin.ir.overrides.FakeOverrideBuilderStrategy.postProcessGeneratedFakeOverride(IrOverridingUtil.kt:32)
	at org.jetbrains.kotlin.ir.overrides.IrOverridingUtil.createAndBindFakeOverride(IrOverridingUtil.kt:444)
	at org.jetbrains.kotlin.ir.overrides.IrOverridingUtil.createAndBindFakeOverrides(IrOverridingUtil.kt:281)
	at org.jetbrains.kotlin.ir.overrides.IrOverridingUtil.generateOverridesInFunctionGroup(IrOverridingUtil.kt:237)
	at org.jetbrains.kotlin.ir.overrides.IrOverridingUtil.buildFakeOverridesForClass(IrOverridingUtil.kt:173)
	at org.jetbrains.kotlin.backend.common.overrides.FakeOverrideBuilder$buildFakeOverrideChainsForClass$2$1.invoke(FakeOverrides.kt:125)
	at org.jetbrains.kotlin.backend.common.overrides.FakeOverrideBuilder$buildFakeOverrideChainsForClass$2$1.invoke(FakeOverrides.kt:124)
	at org.jetbrains.kotlin.backend.common.serialization.signature.PublicIdSignatureComputer.inFile(IdSignatureSerializer.kt:45)
	at org.jetbrains.kotlin.backend.common.serialization.signature.IdSignatureSerializer.inFile(IdSignatureSerializer.kt:215)
	at org.jetbrains.kotlin.backend.common.serialization.DeclarationTable.inFile(DeclarationTable.kt:62)
	at org.jetbrains.kotlin.backend.common.overrides.FakeOverrideBuilder.buildFakeOverrideChainsForClass(FakeOverrides.kt:124)
	at org.jetbrains.kotlin.backend.common.overrides.FakeOverrideBuilder.provideFakeOverrides(FakeOverrides.kt:281)
	at org.jetbrains.kotlin.backend.common.overrides.FakeOverrideBuilder.provideFakeOverrides(FakeOverrides.kt:291)
	at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.postProcess(KotlinIrLinker.kt:226)
	at org.jetbrains.kotlin.ir.backend.js.ic.LoadedJsIr.loadUnboundSymbols(JsIrLinkerLoader.kt:76)
	at org.jetbrains.kotlin.ir.backend.js.ic.JsIrLinkerLoader.loadIr(JsIrLinkerLoader.kt:231)
	at org.jetbrains.kotlin.ir.backend.js.ic.JsIrLinkerLoader.loadIr$default(JsIrLinkerLoader.kt:175)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.loadIrForDirtyFilesAndInitCompiler(CacheUpdater.kt:707)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.loadIrAndMakeIrFragmentGenerators(CacheUpdater.kt:744)
	at org.jetbrains.kotlin.ir.backend.js.ic.CacheUpdater.actualizeCaches(CacheUpdater.kt:768)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.prepareIcCaches(K2JsIrCompiler.kt:615)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:253)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by sunildhiman90** [comment]
Which version of Compose Multiplatform we are using in coil 3?, IT seems above issue is due to version mismatch

**Comment by colinrtwhite** [comment]
Coil 3.0 currently uses `1.6.0-alpha01`. You'll need to use that version as it contains fixes that Coil relies on.
