### ISSUE TITLE
java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not

### ISSUE THREAD

**Issue by crowforkotlin** [coil-kt/coil#2141]
```
Android Verison : 14 
Manufacturer ： XiaoMi
System ： HyperOS
Coil Version ： 2.1.0
```
```text
// Loading this image link will cause failure, but it can also be accessed normally.
https://hi77-overseas.mangafunb.fun/jiushu/5bc43/1678584735070010.png.c1500x.jpg
```
```kotlin
app.imageLoader.enqueue(
            ImageRequest.Builder(itemView.context)
                .listener(
                    onSuccess = { _, _ -> },
                    onError = { _, result ->
                        "CoilVH onError ${result.throwable.stackTraceToString()} \t ${result.request.data}".error()
                        // TODO...
                    },
                )
                .data(imageUrl)
                .target(mImage)
                .build()

```
```text
02:53:59.835  E  │ Thread: main
02:53:59.836  E  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
02:53:59.836  E  │ MangaCoilVH$loadImageWithRetry$$inlined$listener$default$1.onError  (ImageRequest.kt:1060)
02:53:59.836  E  │    TipExtKt.error  (TipExt.kt:26)
02:53:59.836  E  ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
02:53:59.836  E  │ CoilVH onError java.lang.IllegalStateException: BitmapFactory returned a null bitmap. Often this means BitmapFactory could not decode the image data read from the input source (e.g. network, disk, or memory) as it's not encoded as a valid image format.
02:53:59.836  E  │ 	at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:79)
02:53:59.836  E  │ 	at coil.decode.BitmapFactoryDecoder.access$decode(BitmapFactoryDecoder.kt:25)
02:53:59.836  E  │ 	at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:46)
02:53:59.836  E  │ 	at coil.decode.BitmapFactoryDecoder$decode$2$1.invoke(BitmapFactoryDecoder.kt:46)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:52)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:44)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:8)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invoke(Unknown Source:4)
02:53:59.836  E  │ 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
02:53:59.836  E  │ 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:159)
02:53:59.836  E  │ 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt.runInterruptible(Interruptible.kt:43)
02:53:59.836  E  │ 	at kotlinx.coroutines.InterruptibleKt.runInterruptible$default(Interruptible.kt:40)
02:53:59.836  E  │ 	at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.kt:46)
02:53:59.836  E  │ 	at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:199)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:41)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:127)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
02:53:59.837  E  │ 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
02:53:59.837  E  │ 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
02:53:59.837  E  │ 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:126)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:41)
02:53:59.837  E  │ 	at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:75)
02:53:59.837  E  │ 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02:53:59.837  E  │ 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
02:53:59.837  E  │ 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
02:53:59.837  E  │ 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
02:53:59.837  E  │ 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
02:53:59.837  E  │ 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
02:53:59.837  E  │ 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
02:53:59.837  E  │ 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
02:53:59.837  E  │  	 https://hi77-overseas.mangafunb.fun/jiushu/5bc43/1678584735070010.png.c1500x.jpg
```

**Comment by crowforkotlin** [comment]
I tried clearing the local cache data and reinstalling to no avail. Apparently this has something to do with loading links.

**Comment by colinrtwhite** [comment]
Your image is very tall (18,000 pixels) and the size isn't being constrained based on your `ImageRequest`. You need to set a bounding size and likely set `scale(Scale.FIT)` to ensure the image is decoded into memory at a smaller size (2000x2000 should be safe).

**Comment by crowforkotlin** [comment]
Is there any other way to solve this problem? I added scale fit but it has no effect, and this problem will definitely occur with 20588 pixels.
Scale loads 18000 pixels high with no problem
But something went wrong when it reached 20588

[Failure]Pixels Height 20588 ： https://hi77-overseas.mangafunb.fun/wsgegdwclmq/5ea80/1664635536820007.jpg.c800x.jpg
[Success]Pixels Height 18000 ： https://hi77-overseas.mangafunb.fun/jiushu/5bc43/1678584735070010.png.c1500x.jpg

**Comment by crowforkotlin** [comment]
```kotlin
.decoderFactory { source, option, loader ->
                    Decoder {
                        val bitmap = BitmapFactory.decodeStream(source.source.source().inputStream())
                        val result = DecodeResult(drawable =bitmap.toDrawable(app.resources), false)
                        result
                    }
                }
```
                
I checked the source code and rewrote the decodeFactory. Now the 23,000 pixel high image has been loaded and it is very clear. I am not sure what are the risks of this implementation? And I think the implementation of BitmapDecode in Yuanma is relatively complicated. Can you give me some suggestions?

**Comment by crowforkotlin** [comment]
@colinrtwhite
