### ISSUE TITLE
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps

### ISSUE THREAD

**Issue by lieying15** [coil-kt/coil#2284]
java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
                                                                                                    	at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:550)
                                                                                                    	at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:557)
                                                                                                    	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:69)
                                                                                                    	at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:127)
                                                                                                    	at android.graphics.Canvas.drawBitmap(Canvas.java:1504)
                                                                                                    	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
                                                                                                    	at android.widget.ImageView.onDraw(ImageView.java:1360)
                                                                                                    	at android.view.View.draw(View.java:20234)
                                                                                                    	at android.view.View.draw(View.java:20104)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20102)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20102)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20237)
                                                                                                    	at android.view.View.draw(View.java:20104)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20102)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20237)
                                                                                                    	at androidx.core.widget.NestedScrollView.draw(NestedScrollView.java:2328)
                                                                                                    	at android.view.View.draw(View.java:20104)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20237)
                                                                                                    	at android.view.View.draw(View.java:20104)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20102)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20237)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
                                                                                                    	at android.view.View.draw(View.java:20104)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20102)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4337)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4114)
                                                                                                    	at android.view.View.draw(View.java:20237)
                                                                                                    	at eightbitlab.com.blurview.PreDrawBlurController.updateBlur(PreDrawBlurController.java:119)
                                                                                                    	at eightbitlab.com.blurview.PreDrawBlurController$1.onPreDraw(PreDrawBlurController.java:50)
                                                                                                    	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2548)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1529)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7412)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1044)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:839)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:774)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1030)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:207)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6878)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by colinrtwhite** [comment]
https://github.com/coil-kt/coil/issues/159
