### ISSUE TITLE
java.lang.NoSuchMethodError: No direct method <init> ... class Lcoil3/network/NetworkFetcher$Factory

### ISSUE THREAD

**Issue by Andrew0000** [coil-kt/coil#2613]
**Describe the bug**
I use Coil3 with Compose Multiplatform. After updating to the latest version, images do not load at all on Android.

**Logs/Screenshots**
The error:

java.lang.NoSuchMethodError: No direct method <init>(Lkotlin/jvm/functions/Function0;Lkotlin/jvm/functions/Function0;)V in class Lcoil3/network/NetworkFetcher$Factory; or its super classes (declaration of 'coil3.network.NetworkFetcher$Factory' appears in /data/app/~~kzQl4pZZXo7AFV3S32mDNA==/com.***.***-kMqm2XWMN-hduynWX0rKNg==/base.apk!classes36.dex)
                                        	at coil3.network.ktor.KtorNetworkFetcher.factory(KtorNetworkFetcher.kt:13)
                                        	at coil3.network.ktor.internal.KtorNetworkFetcherServiceLoaderTarget.factory(KtorNetworkFetcherServiceLoaderTarget.kt:8)
                                        	at coil3.network.ktor.internal.KtorNetworkFetcherServiceLoaderTarget.factory(KtorNetworkFetcherServiceLoaderTarget.kt:7)
                                        	at coil3.RealImageLoaderKt.addServiceLoaderComponents$lambda$3(RealImageLoader.kt:269)
                                        	at coil3.RealImageLoaderKt.$r8$lambda$xGjjeCDAIKaBkbERqXqEUjIxN7A(Unknown Source:0)
                                        	at coil3.RealImageLoaderKt$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                        	at coil3.ComponentRegistry.fetcherFactories_delegate$lambda$2(ComponentRegistry.kt:33)
                                        	at coil3.ComponentRegistry.$r8$lambda$dJAwMCH26B_eSz_vzGP6LqaRwks(Unknown Source:0)
                                        	at coil3.ComponentRegistry$$ExternalSyntheticLambda0.invoke(D8$$SyntheticClass:0)
                                        	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                        	at coil3.ComponentRegistry.getFetcherFactories(ComponentRegistry.kt:32)
                                        	at coil3.ComponentRegistry.newFetcher(ComponentRegistry.kt:86)
                                        	at coil3.intercept.EngineInterceptor.fetch(EngineInterceptor.kt:151)
                                        	at coil3.intercept.EngineInterceptor.execute(EngineInterceptor.kt:116)
                                        	at coil3.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:32)
                                        	at coil3.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:67)
                                        	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                        	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                        	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                        	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                        	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)

**Version**
Android 14.

coil3 = "**3.0.0-rc02**"
coil3Base = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coil3Core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil3" }
coil3ComposeCore = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil3NetworkCore = { module = "io.coil-kt.coil3:coil-network-core", version.ref = "coil3" }
coil3NetworkKtor = { module = "io.coil-kt.coil3:coil-network-ktor", version = "**3.0.0-alpha08**" }
coil3Svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil3" }
coil3Gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }

**Comment by colinrtwhite** [comment]
Looks like you're using an old version of `io.coil-kt.coil3:coil-network-ktor`. You'll need to update to use either `io.coil-kt.coil3:coil-network-ktor2` or `io.coil-kt.coil3:coil-network-ktor3`.

**Comment by Andrew0000** [comment]
Thank you, I missed the point of dividing into ktor2 and ktor3.
