### ISSUE TITLE
VideoFrameDecoder fails on local file uri

### ISSUE THREAD

**Issue by edenman** [coil-kt/coil#2625]
**Describe the bug**
Video doesn't show a preview frame.  Images load fine using the same `@Composable`
```
2024-11-01 16:20:30.274 14767-14767 RealImageLoader         com.my.package                  I  🚨 Failed - file:///data/user/0/com.my.package/cache/path/to/video.mp4 - java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
2024-11-01 16:20:30.323 14767-14767 RealImageLoader         com.my.package                  I  💾 Successful (DISK) - file:///data/user/0/com.my.package/cache/path/to/image.jpg
```

**To Reproduce**
```
    val imageRequest = ImageRequest.Builder(LocalContext.current)
        .data(uri)
        .crossfade(true)
        .build()
    AsyncImage(
        model = imageRequest,
        placeholder = ColorPainter(HorizonTheme.colors.secondaryText),
        contentDescription = null, // TODO
        modifier = modifier,
    )
```

My ImageLoader is pretty simple
```
ImageLoaderFactory {
        ImageLoader.Builder(context)
            .components {
                add(VideoFrameDecoder.Factory())
                add(ImageDecoderDecoder.Factory())
            }
            .okHttpClient { sharedOkHttpClient }
            .build()
    }
```

**Version**
Coil 2.6.0
testing on a Pixel 4

**Comment by edenman** [comment]
The file in question, but this happens for all video files afaict
https://github.com/user-attachments/assets/87fc98f3-5340-4406-b9ae-4a659fae3a78

**Comment by edenman** [comment]
```
java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:281)
	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:247)
	at coil.decode.VideoFrameDecoder.setDataSource(VideoFrameDecoder.kt:204)
	at coil.decode.VideoFrameDecoder.decode(VideoFrameDecoder.kt:42)
	at coil.intercept.EngineInterceptor.decode(EngineInterceptor.kt:203)
	at coil.intercept.EngineInterceptor.access$decode(EngineInterceptor.kt:42)
	at coil.intercept.EngineInterceptor$execute$executeResult$1.invokeSuspend(EngineInterceptor.kt:131)
	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:8)
	at coil.intercept.EngineInterceptor$execute$executeResult$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:42)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:164)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at coil.intercept.EngineInterceptor.execute(EngineInterceptor.kt:130)
	at coil.intercept.EngineInterceptor.access$execute(EngineInterceptor.kt:42)
	at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:77)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

**Comment by colinrtwhite** [comment]
What's the URI scheme (i.e. it is a `content://` URI, a file path, or loaded from the network)? I tried loading the video with the latest `3.0.0-rc02` version and it worked OK:

<img src="https://github.com/user-attachments/assets/caa3bb0a-9c59-468a-975f-8709b990881f" width=50%/>

It's possible this is a hardware or API-specific bug.

**Comment by edenman** [comment]
Yeah file:// path. I’ll try another device on Monday

**Comment by edenman** [comment]
No luck on other devices.  Tried updating my main test device to android 14, no luck.  Updated to Coil 3.0 rc2.  Same issue.  Gotta be something about the file path, will keep digging.

**Comment by edenman** [comment]
There was a colon in the folder name, if I remove that everything works great 🤣 😭 .

**Comment by colinrtwhite** [comment]
Ah nice find. I think Coil 3 should better support path names with different characters since we use a custom `Uri` class instead of `android.net.Uri`.
