### ISSUE TITLE
TooManyRequestsException

### ISSUE THREAD

**Issue by hardbobby** [coil-kt/coil#28]
**Describe Bug**
To ManyRequest Exception on scroll recyclerview

**Reproduce**
Create recyclerview with the adapter using image url and scrolling from top list to bottom list with repeatedly

**Error Message**

> E/UncaughtException: android.net.ConnectivityManager$TooManyRequestsException
        at android.net.ConnectivityManager.convertServiceException(ConnectivityManager.java:2888)
        at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:3061)
        at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3366)
        at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3348)
        at coil.network.NetworkObserverStrategyApi21.start(NetworkObserverStrategy.kt:102)
        at coil.network.NetworkObserver.<init>(NetworkObserver.kt:27)
        at coil.RealImageLoader.<init>(RealImageLoader.kt:94)
        at coil.ImageLoaderBuilder.build(ImageLoaderBuilder.kt:177)

and I use this code for load image url 

````
val cacheDirectory = context.cacheDir
        val cacheSize:Long = 200
        val cache = Cache(cacheDirectory, cacheSize)
        val client = OkHttpClient.Builder().cache(cache).build()

        val imageLoader = ImageLoader(context) {
            availableMemoryPercentage(0.25)
            bitmapPoolPercentage(0.25)
            crossfade(true)
            placeholder(context.getDrawable(R.drawable.ic_picture_placeholder))
            allowRgb565(true)
            okHttpClient(client)

        }
        imageView?.load(uri, imageLoader) {
            memoryCachePolicy(CachePolicy.DISABLED)
            diskCachePolicy(CachePolicy.DISABLED)
        }
````
is it possible to use a signature like Glide did it before, and they reload image from cache first if the image already loaded before?

**Comment by Jawnnypoo** [comment]
You will want to create a single `ImageLoader` outside of the RecyclerView adapter and set it as the default via `Coil.setDefaultImageLoader`, potentially in your `Application.onCreate`. See the sample for an example setup.
