### ISSUE TITLE
GIF-image with CircleCropTransformation not displayed on older devices

### ISSUE THREAD

**Issue by takke** [coil-kt/coil#289]
**Describe the bug**
When displaying GIF images using CircleCropTransformation on Nexus 5 with Android 6.0, IllegalStateException happen.

**Expected behavior**
Displayed cropped image.

**To Reproduce**
```kotlin
        findViewById<ImageView>(R.id.helloImage1R).load(imageUrl1) {
            transformations(CircleCropTransformation())

            listener(onError = {_, throwable ->
                Log.e(tag, imageUrl1, throwable)
            })
        }
```

```xml
        <ImageView
            android:id="@+id/helloImage1R"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            />
```

exception:
```
    java.lang.IllegalStateException: input.config must not be null
        at coil.transform.CircleCropTransformation.transform(CircleCropTransformation.kt:30)
        at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:511)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

See sample project: https://github.com/takke/CoilGifCircleCropErrorSample

When I set layout_width/layout_height, it displayed properly.

```xml
        <ImageView
            android:id="@+id/helloImage1R"
            android:layout_width="100dp"
            android:layout_height="100dp"
            tools:src="@mipmap/ic_launcher"
            />
```

**Logs/Screenshots**

on Nexus5 / Android 6.0
![image](https://user-images.githubusercontent.com/73930/74308307-301a5580-4dab-11ea-87cf-ad8a36465970.png)

on Pixel 3a / Android 10
![image](https://user-images.githubusercontent.com/73930/74308281-209b0c80-4dab-11ea-9bda-d0c2d2b2dda0.png)

**Version**

coil:0.9.5

occur on Android 6.0 (23)

not occur on Android 10 (29)

**Comment by takke** [comment]
After setting the `size` parameter, it was displayed properly. so this issue is not so serious for me.

Thanks.

**Comment by colinrtwhite** [comment]
Thanks for the report + sample project. I've added a fix in master which can be accessed via [snapshot](https://coil-kt.github.io/coil/faq/#how-do-i-get-development-snapshots).
