### ISSUE TITLE
Coil incorrectly calculates result bitmap's width which results in crashes.

### ISSUE THREAD

**Issue by K1rakishou** [coil-kt/coil#422]
**Describe the bug**
I'm trying to load an image with explicitly set image size. Below is a minimal reproducible example:

```
 override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    val imageLoader = ImageLoader.Builder(this).build()

    loadImage(imageLoader)
  }

  private fun loadImage(imageLoader: ImageLoader) {
    val request = with(LoadRequest.Builder(this)) {
      data("https://i.imgur.com/RuWzHVK.png")
      
      // Phone's screen size
      size(1440, 2880)

      target(
        onSuccess = { drawable ->
          image_view.setImageDrawable(drawable)
        }
      )

      build()
    }

    imageLoader.execute(request)
  }
```

But at some point, inside BitmapFactoryDecoder.decode() the library incorrectly calculates the scale of the result bitmap and it ends up with 12000px width which of course crashes the app when trying to render such bitmap. 

![image](https://user-images.githubusercontent.com/10332458/83898147-3324c180-a75f-11ea-92ff-0d6db86bf06f.png)

Removing the "size(1440, 2880)" resolves this issues but this is not an ideal solution.

**Logs/Screenshots**
```
java.lang.RuntimeException: Canvas: trying to draw too large(136500480bytes) bitmap.
        at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:280)
        at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
        at android.widget.ImageView.onDraw(ImageView.java:1434)
        at android.view.View.draw(View.java:21421)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.updateDisplayListIfDirty(View.java:20289)
        at android.view.View.draw(View.java:21153)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
        at android.view.View.draw(View.java:21424)
        at com.android.internal.policy.DecorView.draw(DecorView.java:806)
        at android.view.View.updateDisplayListIfDirty(View.java:20298)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:575)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:581)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:654)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3610)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3418)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2755)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:725)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Version**
coil version 0.11.0, Android API version 29.

**Comment by colinrtwhite** [comment]
Thanks for the report. It looks like the request is using `Scale.FILL` (the default scale) for calculating how to fit the image into the requested size. Can you try using `scale(Scale.FIT)` and see if that fixes the issue? `Scale.FIT` fits the maximum image dimension to the minimum requested dimension whereas `Scale.FILL` does the opposite.

Also if you use `target(imageView)` Coil will detect the scale automatically from the `ImageView`'s scaleType.

**Comment by joshallenit** [comment]
Hi, was this fixed, or was it closed because of the `Scale.FIT` work around?
