### ISSUE TITLE
Creating default OkHttp Cache can trigger strict mode violation.

### ISSUE THREAD

**Issue by saschpe** [coil-kt/coil#48]
**Describe the bug**
See strict mode warning below.

**To Reproduce**
Use *Image.load()* from inside a RecyclerView.Adapter. I didn't see it happening when it's used from inside a Fragment.

**Expected behavior**
**Dispatchers.IO** should be used. It also wouldn't hurt to be able to pass a custom lifecycle (actually a different issue) as well.

**Logs/Screenshots**
```
2019-08-19 16:00:08.236 17277-17277/ D/StrictMode: StrictMode policy violation; ~duration=326 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
        at java.io.File.exists(File.java:1152)
        at java.io.File.mkdirs(File.java:1714)
        at coil.util.Utils.getDefaultCacheDirectory(Utils.kt:33)
        at coil.ImageLoaderBuilder.buildDefaultOkHttpClient(ImageLoaderBuilder.kt:189)
        at coil.ImageLoaderBuilder.build(ImageLoaderBuilder.kt:182)
        at coil.Coil.buildDefaultImageLoader(Coil.kt:57)
        at coil.Coil.loader(Coil.kt:20)
...
```

**Library version**
0.6.1

**Comment by colinrtwhite** [comment]
Currently, the OkHttpClient is built synchronously. https://github.com/coil-kt/coil/pull/8 will fix this issue by allowing us to lazily create the OkHttpClient instance on a background thread.

**Comment by colinrtwhite** [comment]
Fix for this has been merged to master. If you need it right away, you can use `0.7.0-SNAPSHOT`: https://github.com/coil-kt/coil/blob/master/docs/faq.md#how-do-i-get-development-snapshots
