### ISSUE TITLE
StrictMode crash decoding a GIF

### ISSUE THREAD

**Issue by alcere** [coil-kt/coil#488]
**Describe the bug**
StrictMode detects a resource acquired but never released, presumably in `ImageDecoderDecoder`
  

> at coil.decode.ImageDecoderDecoder.decode(ImageDecoderDecoder.kt:123)

I can't reproduce using SDK 30

**Expected behavior**

**To Reproduce**
Download a GIF with StrictMode enabled using the following configuration:
 ```
 val vmPolicy = VmPolicy.Builder()
            .detectLeakedClosableObjects()
           
        StrictMode.setVmPolicy(vmPolicy.build())
```

**Logs/Screenshots**
```
D/StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
        at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1877)
        at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:286)
        at java.io.FileInputStream.finalize(FileInputStream.java:493)
        at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:289)
        at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:276)
        at java.lang.Daemons$Daemon.run(Daemons.java:137)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:237)
        at java.io.FileInputStream.<init>(FileInputStream.java:174)
        at android.graphics.ImageDecoder.createFromFile(ImageDecoder.java:296)
        at android.graphics.ImageDecoder.access$600(ImageDecoder.java:173)
        at android.graphics.ImageDecoder$FileSource.createImageDecoder(ImageDecoder.java:535)
        at android.graphics.ImageDecoder.decodeDrawableImpl(ImageDecoder.java:1743)
        at android.graphics.ImageDecoder.decodeDrawable(ImageDecoder.java:1736)
        at coil.decode.ImageDecoderDecoder.decode(ImageDecoderDecoder.kt:123)
        at coil.RealImageLoader$loadData$2.invokeSuspend(RealImageLoader.kt:349)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Version**
Coil version: 0.11.0
Not happening using Android SDK 30

**Comment by colinrtwhite** [comment]
Hmm tracing through the [ImageDecoder source code](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/graphics/java/android/graphics/ImageDecoder.java), this looks like it might be an Android bug. Please file an issue with the Android Graphics team: https://issuetracker.google.com/issues/new?component=192644&template=1438858.
