### ISSUE TITLE
Fix IDE preview

### ISSUE THREAD

**Issue by oh-Rin** [coil-kt/coil#535]
**Is your feature request related to a problem? Please describe.**
There will be errors when using coil to load pictures in the IDE preview. I checked the error log and I think these errors can be fixed

**Describe the solution you'd like**
I don’t know if this part can be cancelled, or if it’s in the ide preview behavior, replace it with a false value
https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/ImageLoader.kt#L115

**Additional context**
> java.lang.AssertionError: Unsupported Service: activity
	at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:669)
	at android.content.Context.getSystemService(Context.java:3705)
	at androidx.core.content.ContextCompat.getSystemService(ContextCompat.java:716)
	at coil.util.Utils.getDefaultAvailableMemoryPercentage(Utils.kt:86)
	at coil.ImageLoader$Builder.<init>(ImageLoader.kt:115)
	at coil.ImageLoader$Companion.create(ImageLoader.kt:497)
	at coil.Coil.newImageLoader(Coil.kt:77)
	at coil.Coil.imageLoader(Coil.kt:24)
	at com.mars.ui.extension.CoilKt.CoilImage$default(Coil.kt:80)
	at com.rin.ui.samples.ebook.MainActivity$Banner$1.invoke(MainActivity.kt:77)
	at com.rin.ui.samples.ebook.MainActivity$Banner$1.invoke(MainActivity.kt:31)

![image](https://user-images.githubusercontent.com/58068445/93202807-e69d4900-f785-11ea-97e4-7a704a094d89.png)

In addition, I saw that the implementation of IDE Preview is a fake android context. Is there a possibility of supporting previewing web pictures?

**Comment by colinrtwhite** [comment]
Just merged #541 which fixes the activity preview. Unfortunately I don't think it's possible to start a network request using the layoutlib bridge context so it's not possible to show a preview of the network image.
