### ISSUE TITLE
InterruptibleSource crashes

### ISSUE THREAD

**Issue by ehehhh** [coil-kt/coil#589]
Hi,

Our company was using Coil for a while with no issues, but lately we've started to receive a number of crashes (both with 1.0.0-rc3 and 1.0.0). 
Looks like it's not tied to a single device or operating system version: it appears on Samsung, Xiaomi, Huawei, OnePlus; running Android 7, 8, 9, 10.
Unfortunately, I haven't been able to reproduce this myself, hoping you can provide some guidance or an explanation.

Thanks in advance for any info you can provide!

Crash stacktrace:
```
Fatal Exception: java.util.concurrent.CancellationException: Blocking call was interrupted due to parent cancellation.
       at coil.decode.InterruptibleSourceKt.withInterruptibleSource$$forInline(InterruptibleSourceKt.java:36)
       at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.java:344)
       at coil.intercept.EngineInterceptor.execute(EngineInterceptor.java:310)
       at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.java:428)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

Caused by java.net.SocketTimeoutException: timeout
       at okio.SocketAsyncTimeout.newTimeoutException(SocketAsyncTimeout.java:144)
       at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.java:162)
       at okio.AsyncTimeout.withTimeout(AsyncTimeout.java:154)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.java:335)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:331)
       at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:368)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:276)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.java:178)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at coil.decode.InterruptibleSource.read(InterruptibleSource.java:78)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.java:279)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.java:158)
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:824)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:799)
       at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.java:170)
       at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.java:28)
       at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.java:41)
       at coil.intercept.EngineInterceptor.execute(EngineInterceptor.java:310)
       at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.java:428)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

Caused by java.net.SocketException: socket is closed
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:554)
       at okio.InputStreamSource.read(InputStreamSource.java:91)
       at okio.AsyncTimeout$source$1.read(AsyncTimeout.java:129)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:331)
       at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:368)
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:276)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.java:178)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at coil.decode.InterruptibleSource.read(InterruptibleSource.java:78)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at coil.decode.BitmapFactoryDecoder$ExceptionCatchingSource.read(BitmapFactoryDecoder.java:279)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.java:158)
       at android.graphics.BitmapFactory.nativeDecodeStream(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:824)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:799)
       at coil.decode.BitmapFactoryDecoder.decodeInterruptible(BitmapFactoryDecoder.java:170)
       at coil.decode.BitmapFactoryDecoder.access$decodeInterruptible(BitmapFactoryDecoder.java:28)
       at coil.decode.BitmapFactoryDecoder.decode(BitmapFactoryDecoder.java:41)
       at coil.intercept.EngineInterceptor.execute(EngineInterceptor.java:310)
       at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.java:428)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:56)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:738)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

**Comment by colinrtwhite** [comment]
@ehehhh Are you sure this is crashing your app and not just logging? This stack trace looks like Coil is cancelling the coroutine. `CancellationException` has special handling in coroutines as it propagates cancellation.

**Comment by ehehhh** [comment]
Yes, this appears both under Crashlytics and under Play Store reports as "Crash" event.

**Comment by colinrtwhite** [comment]
Any `load`/`enqueue` calls are always [caught and reported to the `ImageLoader`'s `Logger`](https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/RealImageLoader.kt#L85) so this would have to be due on an `execute` call. However, uncaught `CancellationException`s in a coroutine shouldn't crash your app.
