### ISSUE TITLE
Canvas: trying to use a recycled bitmap

### ISSUE THREAD

**Issue by skyCracks** [coil-kt/coil#611]
BitmapDrawable: Canvas: trying to use a recycled bitmap
2020-12-12 13:59:15.742 23015-23015/ W/System.err: java.lang.IllegalArgumentException: Software rendering doesn't support hardware bitmaps
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.BaseCanvas.onHwBitmapInSwMode(BaseCanvas.java:632)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.BaseCanvas.throwIfHwBitmapInSwMode(BaseCanvas.java:639)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:73)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:131)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.Canvas.drawBitmap(Canvas.java:1621)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.widget.ImageView.onDraw(ImageView.java:1448)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21635)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21504)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4549)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4308)
2020-12-12 13:59:15.743 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21502)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4549)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4308)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21502)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4549)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4308)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at com.ruffian.library.widget.RRelativeLayout.dispatchDraw(RRelativeLayout.java:40)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21638)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21504)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4549)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4308)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at android.view.View.draw(View.java:21638)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at androidx.core.view.ViewKt.drawToBitmap(View.kt:231)
2020-12-12 13:59:15.744 23015-23015/ W/System.err:     at androidx.core.view.ViewKt.drawToBitmap$default(View.kt:225)

In Kotlin, this problem occurs when the parent layout calls drawToBitmap() to convert to a bitmap. This problem by setting allowHardware(false)

**Comment by colinrtwhite** [comment]
`Canvas: trying to use a recycled bitmap` and `Software rendering doesn't support hardware bitmaps` are two separate errors. The first can be worked-around by setting `bitmapPoolingEnabled(false)` when creating your `ImageLoader`. The second can be fixed by adding `allowHardware(false)` to your image request.
