### ISSUE TITLE
Using ViewSizeResolver crashes with "java.lang.IllegalStateException: Already resumed, but proposed with update PixelSize(width=1286, height=420)"

### ISSUE THREAD

**Issue by K1rakishou** [coil-kt/coil#627]
Using ViewSizeResolver causes `java.lang.IllegalStateException: Already resumed, but proposed with update` exception.

```
UNCAUGHT: Called from unhandled exception handler.
    java.lang.IllegalStateException: Already resumed, but proposed with update PixelSize(width=1286, height=420)
        at kotlinx.coroutines.CancellableContinuationImpl.alreadyResumedError(CancellableContinuationImpl.kt:447)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:412)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293)
        at coil.size.ViewSizeResolver$size$$inlined$suspendCancellableCoroutine$lambda$1.onPreDraw(ViewSizeResolver.kt:47)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3089)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

The crash is most likely occurs because continuation is resumed twice for some unknown reason here: https://github.com/coil-kt/coil/blob/92c9a0cd8997fe2e0185b8bff2c7dd5404759fc6/coil-base/src/main/java/coil/size/ViewSizeResolver.kt#L47

The temporary solution is to subclass ViewSizeResolver and add this check:
```kotlin
if (continuation.isActive) {
    continuation.resume(size)
}
```

Version: io.coil-kt:coil-base:1.1.0

**Comment by colinrtwhite** [comment]
Interesting - are you able to reproduce this locally? We can work around this as you mentioned, however I'm wondering in what cases the `OnPreDrawListener` is called twice.

**Comment by K1rakishou** [comment]
>Interesting - are you able to reproduce this locally?

Yes this was happening every time.

>however I'm wondering in what cases the OnPreDrawListener is called twice.

Honestly I have no idea. It seems like the onPreDraw callback is not getting removed and that's why it's called twice. But this may also be a bug in my app but I couldn't find anything that could cause it.

**Comment by colinrtwhite** [comment]
@K1rakishou Do you have a layout or code snippet that reproduces the issue? I've uploaded a fix [here](https://github.com/coil-kt/coil/pull/628) that should guard against the issue, but I'm not sure if it solves the root cause.

**Comment by K1rakishou** [comment]
So I tried a couple of things and here is what I found.

1. Everything works when using the default View.doOnPreDraw() extension from core-ktx. (That's really strange because it does pretty much the same as what ViewSizeRelover does).
2. The second call of OnPreDraw listener happens because removePreDrawListenerSafe() removes a different listener for some unknown reason.

```
// First call
OnPreDrawListener=207304544, view=32900121, continuation=257264862, continuation.isActive=true, viewTreeObserver=168611519
removePreDrawListenerSafe() isAlive==false, viewTreeObserver=86796684

// Second call
OnPreDrawListener=207304544, view=32900121, continuation=257264862, continuation.isActive=false, viewTreeObserver=168611519
removePreDrawListenerSafe() isAlive==false, viewTreeObserver=86796684
```

Here we can see that hashcode of viewTreeObserver that we capture in FixedViewSizeResolver.size().suspendCancellableCoroutine {} block is 168611519, however when calling removePreDrawListenerSafe() the viewTreeObserver's hashcode that we remove OnPreDrawListener from is 86796684. So basically we remove a wrong OnPreDrawListener and that's why it's called the second time.

Here is the code I used to test it - https://gist.github.com/K1rakishou/5fa4aaad8f5b31e2a7ecf7b3232c29ae

Here is the code that executes the coil request with ViewSizeResolver - https://github.com/K1rakishou/Kuroba-Experimental/blob/86b5f33df07eb47773d22f3bbc2ca6c642ef24ae/Kuroba/app/src/main/java/com/github/k1rakishou/chan/core/image/ImageLoaderV2.kt#L267 (The `is ImageSize.MeasurableImageSize -> { ... }` part)
Here is the code that calls that method - https://github.com/K1rakishou/Kuroba-Experimental/blob/f0537adc187e743cd1f2f91abcc41d9760895d65/Kuroba/app/src/main/java/com/github/k1rakishou/chan/features/reply/epoxy/EpoxyReplyFileView.kt#L99 (I'm using Epoxy)

There is a lot of stuff going on so it's going to be really hard to extract a minimal reproducible example.

**Comment by colinrtwhite** [comment]
Interesting - thanks for looking into it. Doesn't look like your code is doing anything unexpected. If the view tree observer is not alive, we cannot call `removeOnPreDrawListener` or it throws, however if we don't call `removeOnPreDrawListener` the dead view tree observer may call `onPreDraw` a second time. Given this, I think the safest thing is to guard against multiple resumes like in #628.
