### ISSUE TITLE
Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by tprochazka** [coil-kt/coil#690]
We tried to switch to Coil already a year ago and now again and it always fails on "trying to use a recycled bitmap". We were using UniversalImageLoader (now obsolete), Picassa, and Glider and there is no issue like that.  But Coil is awesome and we would like to migrate all libraries to it.

I know that you already closed several reports like this just be `bitmapPoolingEnabled(false)`. 
But would be great to understand it a little bit more. 

- What are the disadvantages of this action? Has this any impact?
- Is this something that Glider or Picassa also have?
- Has `bitmapPooling` effect only when I want to display the same image several times on screen, like some iconography, and no effect when I'm using it for displaying photos thumbnail, where every photo is different? Or I don't understand it correctly?
- Is it possible that it is just some type of synchronization issue or race condition? 
- Or do you think that it is just an Android platform bug? 

```
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@a6adeab
       at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:87)
       at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:278)
       at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:91)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
       at android.widget.ImageView.onDraw(ImageView.java:1434)
       at android.view.View.draw(View.java:23191)
       at android.view.View.updateDisplayListIfDirty(View.java:22066)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23194)
       at android.view.View.updateDisplayListIfDirty(View.java:22066)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23194)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
       at android.view.View.updateDisplayListIfDirty(View.java:22066)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1975)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.updateDisplayListIfDirty(View.java:22052)
       at android.view.View.draw(View.java:22921)
       at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
       at android.view.View.draw(View.java:23194)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1114)
       at android.view.View.updateDisplayListIfDirty(View.java:22066)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4263)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4047)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3320)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
       at android.view.Choreographer.doCallbacks(Choreographer.java:794)
       at android.view.Choreographer.doFrame(Choreographer.java:729)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7860)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by colinrtwhite** [comment]
@tprochazka Sure, happy to provide a bit more clarity:

- No, the memory cache is not disabled if bitmap pooling is disabled. All functionality remains the same. Bitmap pooling is only changes performance.
- Glide requires bitmap pooling and does not allow you to disable it. Picasso does not support bitmap pooling.
- `ImageViewTarget` implements `PoolableViewTarget` so using `imageView.load` will use bitmap pooling unless it's disabled with `bitmapPollingEnabled(false)`.
- Bitmap pooling will re-use an existing bitmap in memory to draw a new image. e.g. if you load an image into an `ImageView` in a `Fragment` and then you destroy that `Fragment` when navigating to a different `Fragment`, the `Bitmap` that was created to load the image into that `Fragment`'s `ImageView` will be re-used for a subsequent image request.

The exception you're running into can occur for a number of reasons. It's possible it's triggered by framework issues on certain API levels/devices, however more often it's caused by users not adhering to the contract set in `PoolableViewTarget`'s documentation. For instance, using `imageView.load` then calling `imageView.getDrawable().bitmap` and using the bitmap elsewhere. This breaks Coil's bitmap reference counter and can result in the above exception.

Overall, I wouldn't worry about setting `bitmapPooling(false)`. I've talked with the Android framework graphics team and bitmap pooling is only most effective on API 22 and below. Bitmap pooling is very restrictive and the performance benefits of it are unproven on API 23+. Picasso doesn't support bitmap pooling and is quick nonetheless. It's possible the next major version of Coil won't support bitmap pooling, though I'd need to do more performance to quantify the change before then.

**Comment by tprochazka** [comment]
Thanks a lot.
So thumbnail is cached in memory in which way? As JPG? So then the only thing that happens without pooling is that image needs to be decoded back to the Bitmap object for displaying? But in-memory cache, has already a small size, so this operation will be very fast anyway, especially on 23+ devices right?

**Comment by akardas16** [comment]
if anyone face this issue check yourBitmap.isRecycled is not true. if it is true then copy bitmap to in a new bitmap and use new bitmap. 
```
val newBitmap = drawable?.toBitmap()?.copy()
if (newBitmap?.isRecycled?.not() == true){}
```
