### ISSUE TITLE
VideoFrameDecoder fails decoding mp4

### ISSUE THREAD

**Issue by alcere** [coil-kt/coil#732]
**Describe the bug**
Getting a video frame from an online resource fails for mp4 files, it works fine for .mov files.

**Expected behavior**

**To Reproduce**
```
  private val imageLoader = ImageLoader.Builder(binding.root.context)
        .componentRegistry {
            add(VideoFrameFileFetcher(binding.root.context))
            add(VideoFrameUriFetcher(binding.root.context))
            add(VideoFrameDecoder(binding.root.context))
        }
        .logger(DebugLogger(Log.VERBOSE))
        .build()

imageView.load("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4", imageLoader = imageLoader)
```

**Logs/Screenshots**
```
Failed - http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4 - java.lang.IllegalArgumentException
E/RealImageLoader: java.lang.IllegalArgumentException
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:173)
        at coil.fetch.VideoFrameUriFetcher.setDataSource(VideoFrameFetcher.kt:50)
        at coil.fetch.VideoFrameUriFetcher.setDataSource(VideoFrameFetcher.kt:35)
        at coil.fetch.VideoFrameFetcher.fetch$suspendImpl(VideoFrameFetcher.kt:72)
        at coil.fetch.VideoFrameFetcher.fetch(Unknown Source:0)
        at coil.intercept.EngineInterceptor$intercept$2.invokeSuspend(EngineInterceptor.kt:403)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
**Version**
1.2.0

**Comment by alcere** [comment]
Works fine with : https://file-examples-com.github.io/uploads/2018/04/file_example_MOV_480_700kB.mov

**Comment by colinrtwhite** [comment]
If you use `https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4` (HTTPS) does it work? Android prevents unsecured traffic by default.

**Comment by alcere** [comment]
It doesn't work either, same error :(

**Comment by colinrtwhite** [comment]
@alcere Figured out the issue. You can work-around it by removing `VideoFrameUriFetcher` like this (it's safe to do so):

```kotlin
private val imageLoader = ImageLoader.Builder(binding.root.context)
        .componentRegistry {
            add(VideoFrameFileFetcher(binding.root.context))
            add(VideoFrameUriFetcher(binding.root.context))
            add(VideoFrameDecoder(binding.root.context))
        }
        .logger(DebugLogger(Log.VERBOSE))
        .build()
```

The issue will be fixed in an upcoming patch release.

**Comment by alcere** [comment]
Thanks for the quick reply!!
