### ISSUE TITLE
Disabling the Memory Cache crashes the app

### ISSUE THREAD

**Issue by hansenji** [coil-kt/coil#83]
**Describe the bug**
When set the `availableMemoryPercentage` to `0.0` it crashes the app in the LruCache

**To Reproduce**
 ```
Coil.setDefaultImageLoader {
    ImageLoaderBuilder(application)
        .availableMemoryPercentage(0.0)
        .build()
}
```

**Expected behavior**
Setting availableMemoryCache to 0 disables the cache not crashes.

**Logs/Screenshots**
```
java.lang.IllegalArgumentException: maxSize <= 0
        at androidx.collection.LruCache.<init>(LruCache.java:53)
        at coil.memory.MemoryCache$cache$1.<init>(MemoryCache.kt:24)
        at coil.memory.MemoryCache.<init>(MemoryCache.kt:24)
        at coil.RealImageLoader.<init>(RealImageLoader.kt:93)
        at coil.ImageLoaderBuilder.build(ImageLoaderBuilder.kt:177)
```

**Library version**
0.6.1

**Comment by colinrtwhite** [comment]
Thanks for reporting the issue. I'll add the fix to the `0.7.0` release.
