### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by saschpe** [coil-kt/coil#93]
**Describe the bug**
When an app makes use of Robolectric and tests fragments or activities which in turn use Coil to load images, the default image loader needs to be initialized manually (via *CoilContentProvider*). The canonical way to do this with Robolectric would be to put this in a @Before method in a JUnit4 based unit test class or a custom **Application** instance:
```kotlin
Robolectric.setupContentProvider(CoilContentProvider::class.java)
```
This doesn't work though as CoilContentProvider is internal. So the most viable option is 
```kotlin
Coil.setDefaultImageLoader(ImageLoader(ApplicationProvider.getApplicationContext()))
```

**To Reproduce**
Invoke a unit test for a fragment or activity using coil (e.g. with *launchFragmentInContainer*, the new way to test fragments).

**Expected behavior**
The usage of **setDefaultImageLoader** is a little hidden in the existing documentation. Ideally, a dedicated *Testing* page with a paragraph on Robolectric would be good (I'm willing to start writing it) and / or **CoilContentProvider** is marked as [@VisibleForTesting](https://developer.android.com/reference/android/support/annotation/VisibleForTesting).

**Logs/Screenshots**
```
java.lang.Exception: Main looper has queued unexecuted runnables. This might be the cause of the test failure. You might need a shadowOf(getMainLooper()).idle() call.
	at org.robolectric.android.internal.AndroidTestEnvironment.checkStateAfterTestFailure(AndroidTestEnvironment.java:470)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:548)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized
	at coil.util.CoilContentProvider$Companion.getContext$coil_default_release(CoilContentProvider.kt:17)
	at coil.Coil.buildDefaultImageLoader(Coil.kt:48)
	at coil.Coil.loader(Coil.kt:20)
```

**Library version**
0.7.0

**Comment by colinrtwhite** [comment]
Thanks for the report. Similar libraries have their init ContentProviders set to public so I think it makes sense to do the same for Coil.
