### ISSUE TITLE
Fetcher.key() blocks UI thread 

### ISSUE THREAD

**Issue by mikepenz** [coil-kt/coil#97]
**Describe the bug**

Currently the `key()` method of `Fetchers` is called from the UI thread, which results in a `StrictMode` violation for the `FileFetchers`. As it uses the `.lastModified()` method. 

https://github.com/coil-kt/coil/blob/master/coil-base/src/main/java/coil/fetch/FileFetcher.kt#L14

**To Reproduce**
- Enable StrictMode in your application
- Load an Image via coil via the normal `view.load()` syntax
- StrictMode will complain about this violation
- The violation is minimal, but in various cases this can get problematic

**Expected behavior**
- method should also be called from a IO dispatcher so it will not block the UI thread

**Logs/Screenshots**
```
2019-09-12 18:15:20.539 16670-16670 D/StrictMode: StrictMode policy violation; ~duration=1 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at java.io.UnixFileSystem.getLastModifiedTime(UnixFileSystem.java:289)
        at java.io.File.lastModified(File.java:939)
        at coil.fetch.FileFetcher.key(FileFetcher.kt:14)
        at coil.fetch.FileFetcher.key(FileFetcher.kt:12)
        at coil.RealImageLoader.computeCacheKey(RealImageLoader.kt:276)
        at coil.RealImageLoader.access$computeCacheKey(RealImageLoader.kt:78)
        at coil.RealImageLoader$execute$2$deferred$1.invokeSuspend(RealImageLoader.kt:202)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:68)
        at kotlinx.coroutines.DispatchedKt.resumeCancellable(Dispatched.kt:464)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:154)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at coil.RealImageLoader.load(RealImageLoader.kt:137)
```

**Library version**
0.7.0

**Comment by colinrtwhite** [comment]
Thanks for the report. Unfortunately, there isn't a great way to solve this that I know of. `Fetcher.key` needs to be called on the main thread so the `ImageLoader` can check if it's already in the memory cache and set it on the `Target` synchronously.

If we moved this to a background thread, we would have to jump back to the main thread to set the cached image, which could delay setting the cached image enough that we would show the placeholder for the first frame instead.

Going to leave this issue open for discussion for how to fix this while synchronously checking the memory cache.

**Comment by colinrtwhite** [comment]
Unfortunately, there isn't a great way to solve this that I know of. Fetcher.key needs to be called on the main thread so the ImageLoader can check if it's already in the memory cache and set it on the Target synchronously.

If we moved this to a background thread, we would have to jump back to the main thread to set the cached image, which could delay setting the cached image enough that we would show the placeholder for the first frame instead.

Going to leave this issue open for discussion for how to fix this while synchronously checking the memory cache.

**Comment by mikepenz** [comment]
A more generic solution to this problem would be to allow passing in the cache key to use. So the developer could theoretically decide how to deal with the delay. In addition it would allow to provide custom cacheKey logics without the need for custom fetchers. 

```
suspend fun loadImage() {
       val cacheKey = suspendGetCacheKey(entry.data)
       photoView.load(entry.data) {
                cacheKey(cacheKey)
                placeholder(...)
                error(...)
       }
}
```


Totally understand the problem about not wanting to see the placeholder for the first frame, or how long that cache key resolving would need, but I suppose there should either be a warning for the FileFetcher, or the default key logic is adjusted to not use the modifiedDate.

**Comment by colinrtwhite** [comment]
It's already possible to set a custom cache key, which skips calling `Fetcher.key` (and `Transformation.key`) using:

```kotlin
imageView.load("https://www.example.com/image.jpg") {
    key("custom-cache-key")
}
```

**Comment by mikepenz** [comment]
Not sure how I missed that one. 

Anyways from my perspective you may close this. You might want to note somewhere that people who use the `FileLoader` will face the IO on main thread, and that they can use the `key()` method to work around this problem

**Comment by colinrtwhite** [comment]
Sounds good, I'll add a note to `FileLoader`.
